#!/bin/bash
set -e

echo "Starting Python server..."

pip3 install virtualenv
python3 -m virtualenv venv
source venv/bin/activate
pip3 install -r requirements.txt

echo "Setting the OPENAI_API_KEY and starting the server"

OPENAI_API_KEY=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 python app.py
